repo: hxc1216/util-xx
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
  
script:
  - npm run test

after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to Coveralls!"