name: Publish to NPM
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to NPM
        uses: actions/npm@v1
        with:
          args: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
